name: http_cache_hive_store
description: A DB cache store implementation with Hive.
homepage: https://github.com/llfbandit/dart_http_cache/tree/master/http_cache_hive_store
version: 5.0.0

environment:
  sdk: ^3.0.0

dependencies:
  http_cache_core: ^1.0.0

  # https://pub.dev/packages/hive_ce
  hive_ce: ^2.8.0

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^5.0.0
  # https://pub.dev/packages/test
  test: ^1.24.4

  http_cache_store_tester: ^1.0.0
