name: http_cache_file_store
description: A filesystem cache store implementation.
homepage: https://github.com/llfbandit/dart_http_cache/tree/master/http_cache_file_store
version: 2.0.0

environment:
  sdk: ^3.0.0

dependencies:
  http_cache_core: ^1.0.1

  # https://pub.dev/packages/path
  path: ^1.8.0
  # https://pub.dev/packages/synchronized
  synchronized: ^3.0.0

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^5.0.0
  # https://pub.dev/packages/test
  test: ^1.24.4

  http_cache_store_tester: ^1.0.0
