name: dio_cache_interceptor_sembast_store
description: A DB cache store implementation with Sembast for dio_cache_interceptor package.
version: 0.0.1
homepage: https://github.com/murat-ti/dio_cache_interceptor_sembast_store

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio_cache_interceptor: ^3.4.0
  # https://pub.dev/packages/sembast
  sembast: ^3.4.3
  # https://pub.dev/packages/flat_buffers
  flat_buffers: ^2.0.5
  # Dependencies for encryption example
  #encrypt: '>=3.1.0'
  #crypto: '>=2.0.6'

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.3
  # https://pub.dev/packages/lints
  lints: ^2.0.1
  # https://pub.dev/packages/test
  test: ^1.23.1