# Configuration for moor generator
# https://drift.simonbinder.eu/docs/advanced-features/builder_options/
targets:
  $default:
    builders:
      drift_dev:
        options:
          # We don't use companion classes to update partially rows
          # Still generated but will be tree-shaked at compile time.
          data_class_to_companions: false
          apply_converters_on_variables: true
          # Less code generated
          skip_verification_code: true
          override_hash_and_equals_in_result_sets: false
          # Using isolates for the database for better performance
          generate_connect_constructor: true
