name: http_cache_sembast_store
description: A DB cache store agnostic HTTP client implementation with Sembast.
version: 1.0.0
homepage: https://github.com/llfbandit/dart_http_cache/tree/master/dart_http_cache_sembast_store

environment:
  sdk: ^3.0.0

dependencies:
  http_cache_core: ^1.1.1

  # https://pub.dev/packages/sembast
  sembast: ^3.4.4
  # https://pub.dev/packages/sembast_web
  sembast_web: ^2.2.0

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.3
  # https://pub.dev/packages/lints
  lints: ^5.0.0
  # https://pub.dev/packages/test
  test: ^1.24.4

  http_cache_store_tester: ^1.0.0