name: dio_cache_interceptor_mmkv_store
description: A DB cache store implementation with mmkv for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_mmkv_store
version: 1.0.0

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dio_cache_interceptor: ^3.4.4
  messagepack: ^0.2.1
  mmkv: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^3.0.0
  # https://pub.dev/packages/test
  test: ^1.23.1
