# Configuration for moor generator
# https://moor.simonbinder.eu/docs/advanced-features/builder_options/
targets:
  $default:
    builders:
      moor_generator:
        options:
          # We don't use companion classes to update partially rows
          # Still generated but will be tree-shaked at compile time.
          data_class_to_companions: false
          apply_converters_on_variables: true
          # Less code generated
          skip_verification_code: true
          override_hash_and_equals_in_result_sets: false
