name: dio_cache_interceptor_hive_ce_store
description: A DB cache store implementation with Hive CE for dio_cache_interceptor package.
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_hive_ce_store
version: 1.0.0

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  dio_cache_interceptor: ^3.5.0

  # https://pub.dev/packages/hive
  hive_ce: ^2.8.0+2

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^3.0.0
  # https://pub.dev/packages/test
  test: ^1.23.1
