name: dio_cache_interceptor_objectbox_store
description: A DB cache store implementation with ObjectBox for dio_cache_interceptor package.
version: 0.0.1
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_objectbox_store

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio_cache_interceptor: ^3.0.0
  objectbox: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.4
  objectbox_generator: any
  pedantic: ^1.11.0
  test: ^1.16.8