name: http_cache_drift_store
description: A DB cache store implementation with Drift.
homepage: https://github.com/llfbandit/dart_http_cache/tree/master/http_cache_drift_store
version: 7.0.0
environment:
  sdk: ^3.0.0

dependencies:
  http_cache_core: ^1.0.0

  # https://pub.dev/packages/drift
  drift: ^2.9.0
  # https://pub.dev/packages/path
  path: ^1.8.0

dev_dependencies:
  # https://pub.dev/packages/drift_dev
  drift_dev: ^2.5.2
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.3
  # https://pub.dev/packages/lints
  lints: ^5.0.0
  # https://pub.dev/packages/test
  test: ^1.24.4

  http_cache_store_tester: ^1.0.0

  # Dependencies for downloading SQLite before running tests
  http: ^1.1.0
  archive: ^3.3.1
