name: Dart

on:
  push:
    branches: 
      - master
      - gha
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Activate melos
        run: |
          dart pub global activate melos

      - name: Install dependencies
        run: melos bs

      # verify the use of 'dart format' on each commit.
      - name: Verify formatting - dio_cache_interceptor
        working-directory: dio_cache_interceptor
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source - dio_cache_interceptor
        working-directory: dio_cache_interceptor
        run: dart analyze

      - name: Run tests - dio_cache_interceptor
        working-directory: dio_cache_interceptor
        run: |
          flutter test --coverage
      
      - name: Run tests - http_cache_client
        working-directory: http_cache_client
        run: |
          flutter test --coverage

      - name: Run tests - http_cache_core
        working-directory: http_cache_core
        run: |
          flutter test --coverage

      # Run store tests.
      - name: Run tests - Drift store
        working-directory: http_cache_drift_store
        run: |
          flutter test --coverage
      
      - name: Run tests - File store
        working-directory: http_cache_file_store
        run: |
          flutter test --coverage

      - name: Run tests - Hive store
        working-directory: http_cache_hive_store
        run: |
          flutter test --coverage

      - name: Run tests - ObjectBox store
        working-directory: http_cache_objectbox_store
        run: |
          bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)
          flutter test --coverage
      
      - name: Run tests - Sembast store
        working-directory: http_cache_sembast_store
        run: |
          flutter test --coverage
      
      - name: Activate combine_coverage
        run: |
          dart pub global activate combine_coverage

      - name: Merge test coverage
        run: |
          combine_coverage --repo-path=.
      
      - name: Upload global coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: coverage/lcov.info
