name: Dart

on:
  push:
    branches: 
      - master
      - gha
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Activate melos
        run: |
          dart pub global activate melos

      - name: Install dependencies
        run: melos bs

      # verify the use of 'dart format' on each commit.
      - name: Verify formatting - dio_cache_interceptor
        working-directory: dio_cache_interceptor
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source - dio_cache_interceptor
        working-directory: dio_cache_interceptor
        run: dart analyze

      - name: Activate coverage
        run: |
          dart pub global activate coverage

      - name: Run tests with coverage - dio_cache_interceptor
        working-directory: dio_cache_interceptor
        run: |
          dart pub global run coverage:test_with_coverage

      - name: Upload coverage to Codecov dio_cache_interceptor
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: dio_cache_interceptor/coverage/lcov.info
      
      - name: Run tests - http_cache_client
        working-directory: http_cache_client
        run: |
          dart test

      # Run store tests.
      - name: Run tests - Drift store
        working-directory: http_cache_drift_store
        run: |
          dart test
      
      - name: Run tests - File store
        working-directory: http_cache_file_store
        run: |
          dart test

      - name: Run tests - Hive store
        working-directory: http_cache_hive_store
        run: |
          dart test

      # - name: Run tests - Isar store
      #   working-directory: http_cache_isar_store
      #   run: |
      #     dart test

      - name: Run tests - ObjectBox store
        working-directory: http_cache_objectbox_store
        run: |
          bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)
          dart test
      
      - name: Run tests - Sembast store
        working-directory: http_cache_sembast_store
        run: |
          dart test
